/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Organiza
 * API para o app organiza.
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  /** A url do avatar ou imagem do grupo */
  avatarUrl?: string;
  createdAt: string;
  /** Seu e-mail */
  email: string;
  /** uuid */
  id: string;
  /** Seu nome */
  name: string;
  updatedAt: string;
}
